### ISSUE TITLE
Conceptual: A team can be managed though a config.yaml file at the root of the team repo

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/hackathon-leaderboard#1]
Team meta such as `name`, `siteURL`, `contributors`... can be managed through a `config.yaml`, the shape of which is open for disscussion

(This should remain updated with the comments and discussions appearing in this thread)

```yml
teamName: Hacky McHackface
repository: https://github.com/hack0rz/jamstack-hack-2018
siteUrl: https://hacker.netlify.com
contributors:
  - @hack0rz
  - @bouncey
  - @ raisedadead
isOlineHackathon: 'true'
```
